name: Build Flutter App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Fetch Dependencies and Test
        run: |
          flutter pub get
          flutter test
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Build Linux App
        run: flutter build linux --release
      - name: Make Linux App Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}-linux-x64-release
          path: build/linux/x64/release/bundle
      
      - name: Build Android App APKs
        run: flutter build apk --release
      - name: Make Android App APKs Build Artifact (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}-android-armeabi-v7a-release
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - name: Make Android App APKs Build Artifact (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}-android-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk